# Save this to your $HOME directory as `.tp.toml`
# Or save it to the repository's root directory as `.tp.toml`
# Currently expects TOML -- https://toml.io
# TOML is case-sensitive | Keys are mixedCase

# binary: (type: string) The name of the binary, expect either 'tofu' or 'terraform'. Must exist on your $PATH. Only required if both binaries exist on your $PATH.
# binary = ''
# planFile: (type: string) The name of the plan file created by 'gh tp'.
planFile = ''
# mdFile: (type: string) The name of the Markdown file created by 'gh tp'.
mdFile = ''
# verbose: (type: bool) Enable Verbose Logging. Default is false.
verbose = false
