# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -s -w
      - -X github.com/esacteksab/gh-tp/cmd.Version={{.Tag}}
      - -X github.com/esacteksab/gh-tp/cmd.Date={{time "2006-01-02"}}
      - -X github.com/esacteksab/gh-tp/cmd.Commit={{.ShortCommit}}
      - -X github.com/esacteksab/gh-tp/cmd.BuiltBy=goreleaser
archives:
  - formats: binary
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- .Tag }}_
      {{- title .Os }}-
      {{- .Arch }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: zip

changelog:
  use: github

release:
  draft: true
